# Generated by Django 5.2.12 on 2026-03-31 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0004_alter_payroll_allowances_alter_payroll_basic_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='monthly_leave_quota',
            field=models.PositiveIntegerField(default=2, help_text='Monthly leave quota assigned by admin.'),
        ),
    ]
